name: main
#description: "Example of running Figmagic in CI through the Figma GitHub Actions plugin"

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message. What changes were made?'
        required: false
        default: 'Updated Figma'
      branch:
        description: 'Branch name'
        required: false
        default: 'main'
      version:
        description: 'Which version of the Figma document to use?'
        required: false
        default: 'Latest'
  push:
    branches:
      - "main"

jobs:
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        node-version: [14.x]
    steps:
      - run: echo "MESSAGE --- ${{ github.event.inputs.message }}"
      - run: echo "BRANCH --- ${{ github.event.inputs.branch }}"
      - run: echo "VERSION --- ${{ github.event.inputs.version }}"
      - name: Checkout
        uses: actions/checkout@v2
        id: checkout

      - name: Install Figmagic
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
        id: node

      - run: npm install -D figmagic

      - name: Run Figmagic and use latest data, with Node.js ${{ matrix.node-version }}
        id: figma-latest
        if: github.event.inputs.version == 'Latest'
        run: node node_modules/figmagic/build/index.js

      - name: Run Figmagic and named version of Figma data, with Node.js ${{ matrix.node-version }}
        id: figma-versioned
        if: github.event.inputs.version != 'Latest'
        run: node node_modules/figmagic/build/index.js -- --versionName ${{ github.event.inputs.version }}
