name: main

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Optional message - What changed?'
        required: false
        default: 'No message'
      version:
        description: 'Figma file version name'
        required: false
        default: 'latest'
  push:
    branches:
      - "main"
      - "feature/*"
      - "feature/**"
      

jobs:
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        node-version: [14.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        id: checkout

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
        id: node
      - run: npm install -g triplecheck-cli
      - run: triplecheck
