name: main
#description: "Example of running Figmagic in CI through the Figma GitHub Actions plugin"

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Message. What changes were made?'
        required: false
        default: 'Updated Figma'
      branch:
        description: 'Branch name'
        required: false
        default: 'main'
      version:
        description: 'Which version of the Figma document to use?'
        required: false
        default: 'Latest'
  push:
    branches:
      - "main"
    inputs:
      version:
        description: 'Which version of the Figma document to use?'
        required: false
        default: 'Latest'

jobs:
  build-unix:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        node-version: [14.x]
    steps:
      - name: Inputs
        id: input-messages
        run: |
          echo "MESSAGE ---> '${{ github.event.inputs.message }}'"
          echo "BRANCH  ---> '${{ github.event.inputs.branch }}'"
          echo "VERSION ---> '${{ github.event.inputs.version }}'"

      - name: Checkout
        id: checkout
        uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        id: node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Figmagic
        id: install
        run: npm install -D figmagic

      - name: Run Figmagic and use latest Figma data
        id: figma-latest
        if: !${{ github.event.inputs.version }}
        run: node node_modules/figmagic/build/index.js

      - name: Run Figmagic and use named version of Figma data
        id: figma-versioned
        if: ${{ github.event.inputs.version }}
        run: node node_modules/figmagic/build/index.js -- --versionName ${{ github.event.inputs.version }}
